name: Films API Tests

on:
  pull_request:
  workflow_call:

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check repo not fork and public
        run: |
          REPO=$(curl -H "Accept: application/vnd.github+json" "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}")
          if jq -er '.fork' <<<"$REPO" > /dev/null; then
            FORK=$(jq '.fork' <<< "$REPO")
            if [[ $FORK = "true" ]]
            then
              echo "Use the repository automatically created by Yandex Practicum (works in fork repositories are not accepted)"
              echo "Используйте только репозиторий созданный Yandex Practicum, работы в форк репозитории не принимаются"
              exit -1
            fi
          else
            if [[ $GITHUB_REPOSITORY_OWNER = "yandex-praktikum" ]]
            then
              echo "Use the repository automatically created by Yandex Practicum (works in fork repositories are not accepted)"
              echo "Используйте только репозиторий созданный Yandex Practicum, работы в форк репозитории не принимаются"
              exit -2
            fi
            if [[ $GITHUB_REPOSITORY_OWNER != "praktikum-java" ]]
            then
              echo "Share your repository, make it public"
              echo "Откройте доступ к вашему репозиторию, сделайте его публичным"
              exit -3
            fi
          fi

  build-filmorate:

    needs: check-repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install helper script
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget &&
          wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          chmod a+x /tmp/wait-for-it.sh

      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: 'yandex-praktikum/java-filmorate'
          ref: ${{ github.event.pull_request.head.ref }}
          path: tests

      - name: Check and Build application
        run: |
          chmod a+x ./tests/.github/workflows/build.sh
          ./tests/.github/workflows/build.sh

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Application
        run: |
          chmod a+x ./tests/.github/workflows/run.sh
          ./tests/.github/workflows/run.sh


      - name: Waiting for application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:8080
          echo "Application is up"

      - name: Run POSTMAN tests
        run: >
          newman run ./tests/postman/sprint.json 
          --delay-request 50 -r cli,htmlextra 
          --verbose --color on --reporter-htmlextra-darkTheme 
          --reporter-htmlextra-export reports/shareIt.html
          --reporter-htmlextra-title "Отчет по тестам"
          --reporter-htmlextra-logs true
          --reporter-htmlextra-template ./tests/.github/workflows/dashboard-template.hbs


      - name: Upload log artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: filmorate_log
          path: ./*.log

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: postman_tests_report
          path: reports
